name: shortnamelongdescriptionaaaa aaaa aaaa aaa
description: |
  This is going to be a really long named catalog template.  It will have lots of text and the description will as well. This is going to be a really long named catalog template.  It will have lots of text and the description will as well. This is going to be a really long named catalog template.  It will have lots of text and the description will as well. This is going to be a really long named catalog template.  It will have lots of text and the description will as well.
version: 1.0.0
category: Test
projectURL: amazon.com
