all-question-types:
  image: busybox
  labels:
    io.rancher.container.start_once: true
  command: 'su -c "sleep 20 && exec /bootstrap-hdfs.sh" hdfs'
  labels:
    test.certificate: ${TEST_CERTIFICATE}
