name: Affinity Test 1
description: |
  This template sets up a service that has a label.  Then creates another service that relies on that label.  Both should end up on the same host.
version: 2.0.0
category: Test
maintainer: Tani Fiducciaw
license: 9087 licensess
projectURL: http://www.google.com
labels:
  io.rancher.certified: Certified
  color:red

