version: '2'
services:
  loadbalancer:
    image: rancher/lb-service-haproxy:v0.6.2
    ports:
    - 443:443/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'