name: Minimum Version Test 1
description: |
  Checking that rc10 is lower than rc3 so it should still be available
version: 1.0.0
category: test
labels:
  certified:
      rancher:
        rancher: Rancher Labs
        partner: Official
      pl:
        rancher: Core
        partner: Official