.catalog:
  name: "All Question Types"
  version: "1.0.0"
  description: "All the things"
  uuid: all-question-types-0
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "TEST_CERTIFICATE"
      label: "Certificate"
      description: “This is a queried test cert field”
      required: true
      default: "rancher.rocks"
      type: "certificate"
    - variable: "TEST_UNKNOWN"
      label: "Unknown"
      required: false
      default: "wha?"
      type: "unknown"

