version: '2'
.catalog:
  name: "Services with advanced options"
  version: "2.0"
  description: "Services"
  questions:
    - variable: "TEST_STRING"
      label: "String"
      required: false
      default: "hello"
      type: "string"
services:
  wordpress:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: test-2.example.com
      - path: ''
        priority: 1
        protocol: http
        service: collector
        source_port: 443
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000
  collector:
    scale: 1
    start_on_create: true