version: '2'
services:
  servicetest2:
    scale: 1
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: ubuntu:14.04.3
    logging: {}
    stdin_open: true
  lb1:
    scale: 1
    lb_config:
      port_rules:
        source_port: 90
        target_port: 90
        service: servicetest2
        protocol: http
    health_check:
      port: 42
      interval: 2000
      unhealthy_threshold: 3
      healthy_threshold: 2
      response_timeout: 20