volume:
  image: leankit/rancher-azurefile-volume
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    VOLUME_NAME: ${name}
    VOLUME_GID: '${gid}'
    VOLUME_UID: '${uid}'
    VOLUME_FILEMODE: '${filemode}'
    VOLUME_DIRMODE: '${dirmode}'
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.start_once: 'true'
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always