version-test:
  image: nginx
  tty: true
  stdin_open: true
  labels:
    test.string: ${TEST_STRING}
    io.rancher.scheduler.affinity:host_label: foo=bar
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=default/service1


 
