all-question-types:
  image: quay.io/rancher/authorized
  labels:
    io.rancher.container.start_once: ‘true’
  command: 'su -c "sleep 20 && exec /bootstrap-hdfs.sh" hdfs'
  labels:
    test.string: ${TEST_STRING}
    test.multiline: ${TEST_MULTILINE}

