all-question-types:
  image: busybox
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: ‘true’
    test.string: ${TEST_STRING}
    test.multiline: ${TEST_MULTILINE}
    test.boolean: ${TEST_BOOLEAN}

